### ISSUE TITLE
Usage of "swap" command.

### ISSUE THREAD

**Issue by pntpareek** [KyQiao/polyLJ#1]
Do I need to specify different types of atoms in lammps to use "swap" command? Can you please give an example of an input script which uses MD+MC using these codes.

**Comment by KyQiao** [comment]
Please see the update

**Comment by pntpareek** [comment]
Thank you very much for your help.

**Comment by KyQiao** [comment]
I think that's a typo. Fix that later.
Using too many swap steps will be time-consuming so I change that to a small number.

Temperature threshold means you can swap particles under some T. Usually we need to use this to make stable glass, so it won't make sense to start swapping at a high temperature. If you need to swap all the time, just set T to a very high number, say 100.

The initial energy may be high if you start your system in a high-density region. So I usually start with a low-density big box setting and use NPT to compress it into a smaller system.

**Comment by pntpareek** [comment]
Thanks for the clarification.

**Comment by pntpareek** [comment]
Dear KyQiao,

I want to confirm that I do not need the files rma_mutex.cpp, rma_mutex.hpp and vptree.hpp to install in lammps. Also, I guess there is still a typo in fix swap command i.e. for "fix  swap all swap 100 400 111821 0.1" means after every 100 md steps make 400 mc attempts.

I would be grateful if you clear these queries as well.

Best Regards
Puneet

**Comment by KyQiao** [comment]
You're right. It's a typo.
The other cpp file(rma_mutex.cpp, rma_mutex.hpp and vptree.hpp) is used to make the swap process become MPI-multiprocess, which I didn't implement yet. I've already validated the algorithm in OpenMP. So, yes, you don't need them.

**Comment by pntpareek** [comment]
Dear KyQiao,

I am confused about the neighbour list build in this system. Can I keep "neighbour bin 0.3" and "neigh_modify every 1 delay 0 check yes" when I do not use swap and only do MD with NVT for the Berthier Power law polydisperse model? i.e. while only using hybrid md + mc I have to keep "neighbour bin 0.8 (1.62 * 1.25 - 1.25 = 0.775) (here 1.62 is the max. particle size and 1.25 is the cut off)" and "neigh_modify every 20 delay 0 check no"?

I would be grateful if you please reply to this.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I don't think we can do that.

To ensure every particle is included in the range of other particles, we have to check the maximum range(i.e. largest cutoff + skin) and calculate the force.
Otherwise, there will be particles missed.

LAMMPS lacks such a mechanism for the polydisperse system so we need to enlarge the range of neighbor bin+skin and disable "check" to make the system run correctly.

"neigh_modify every 20 delay 0 check no" means we assume the particle won't move too much during 20 steps and we don't want LAMMPS to check if any particle crosses the skin distance since this will trigger the rebuild of neighbor list.


Regards,
Kaiyao



________________________________

**Comment by pntpareek** [comment]
Dear KyQiao,

Thanks for your reply.

Just to confirm that "neigh_modify every 20 delay 0 check no" should be used when I do only MD as well for this polydisperse system?

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

Yes. I think these parameters work for a relatively low temperature.

Regards,
Kaiyao
________________________________

**Comment by pntpareek** [comment]
Dear KyQiao,

Thank you very much for reply. I am very grateful.

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear KyQiao,

I am thankful for your instant replies. I would be grateful if you could please help me in this doubt that I am still confused at.
I was using the Berthier Model for polydispersity for which the maximum particle size is 1.62 and I was using repulsive part of LJ potential having global cut off at 1.25, So 0.775 is the minimum skin distance at T = 0.105 and density 1 (T_MCT ~ 0.1). So while doing NVT only or NVT + Swap I should use the following :-
"neighbor        0.80 bin 
neigh_modify    every 20 delay 0 check no"

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear KyQiao,

Gentle Reminder. I asked you this question because I was using the same procedure for the above system and was not getting the expected result. If you suggest from your experience that the above is correct for this system, then I will start looking for some different issue.

I would be grateful if you please reply.

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear KyQiao,

I understood what you were saying. Thanks for your help. But I am concerned about one thing that when we do minimization the LAMMPS change "every 20 delay 0 check no" to "every 1 delay 0 check yes" automatically, is this going to effect the minimization criteria?

I would be grateful if you please reply.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I haven't done research on the minimization's source code. For me, the MD+MC swap is quite enough to minimize the system.
Building a neighbor list every time seems acceptable if only LAMMPS uses a large bin value as set in "neighbor".


Regards,
Kaiyao


________________________________
发件人: pntpareek ***@***.***>
发送时间: 星期三, 八月 10, 2022 14:16
收件人: KyQiao/polyLJ ***@***.***>
抄送: Kaiyao QIAO ***@***.***>; State change ***@***.***>
主题: Re: [KyQiao/polyLJ] Usage of "swap" command. (Issue #1)


Dear KyQiao,

I understood what you were saying. Thanks for your help. But I am concerned about one thing that when we do minimization the LAMMPS change "every 20 delay 0 check no" to "every 1 delay 0 check yes" automatically, is this going to effect the minimization criteria?

I would be grateful if you please reply.

Best Regards
Puneet

―

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your reply. Would it not be a problem when the "check yes" is used even when "every 1" and large bin value is set in "neighbor"?

I would be grateful if you reply. It would be a great help for me.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I think "check" just triggers a rebuild of the neighbor list when a particle moves into skin distance.
If you already set "every 1" then it doesn't matter.

Regards
Kaiyao
________________________________

**Comment by KyQiao** [comment]
Dear Puneet,

I get what you mean now, maybe you can change "binsize" using "neigh_modify" for multiple times in the run? So "check" also trigger correct rebuild every time.

Regards,
kaiyao
________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your suggestion. I will try implementing that. 

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear Kaiyo,

I do not know why but I checked that my if I take rho_swap = 10, then it gives the time scale of rho_swap = 1 and if I take rho_swap = 100, then it gives the time scale of rho_swap = 10. Have you encountered something like that?

P.S. : -  where rho_swap is defined as ---> Let's say that after every 't_MD' time I attempt 'N_swap' no. of swaps for 'N' no. of particles, then 'rho_swap' = N_swap/(N * t_MD).

I would be grateful if you please reply.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

Thanks for the report. Usually, I will use a fixed parameter. let me check the code.

Regards,
Kaiyao



________________________________

**Comment by pntpareek** [comment]
Dear Kaiyo,

Thanks for your reply.

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear KyQiao,

Let me do all the analysis again. Your code looks correct upto my knowledge. I must confirm again that I am not doing anything wrong on my side.

Best Regards 
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

Let me know if you have any questions.

Regards,
Kaiyao
________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your reply. I will let you know if there are any questions.

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear Kaiyao,

I thought of a way in which neighbor bin can be 0.3 and neighbor list can be (max cut off + bin), but in this I have to use the cut off directly in the code for the polydisperse potential. So for this I will put the max cut off in the "pair_style" command and I put the actual cut off in (rsq < (actual_cut_off)*(sigma_ij2)).

What do you think of this? Can you think of any possible errors arising of this? Would be grateful if you reply.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I do not quite understand what you are going to do, seem like you're trying to hand code the cutoff distance.

Can you show me some code snippets?

Regards,
Kaiyao

________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

You are right. Let me explain in a more elaborate way. In the example given by you for the smallest case of swap, I will change 

>neighbor        1.4 bin 
>neigh_modify        every 20 delay 0 check no             
>pair_style               lj/cut/poly 2.5

to 

>neighbor              0.3 bin
>neigh_modify        every 1 delay 0 check yes             
>pair_style               lj/cut/poly 3.875   (largest cut off = 2.5 * 1.55)

and in the code I will make a change on line 119 of "pair_lj_poly.cpp" which is from

>if (rsq < cutsq[itype][jtype] * sigma_ij2)

to

>if (rsq < 2.5 * 2.5 * sigma_ij2)

and some more changes accordingly. 

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear Kaiyao,

Let me know what do you think?

Thanks and Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I think this also works. It may lose some flexibility on changing the global cutoff, but it's good as long as it works.

This may also avoid some changes to code when simulation comes to the high temperature.

Regards,
Kaiyao

________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your reply.

Best Regards
Puneet

**Comment by pntpareek** [comment]
Dear Kaiyao,

I have done the analysis again and found that there might be some be some issue in "generate.py" for berthier model distribution. I got correct results when I used my own code for generating the distribution.

Thanks and Regards
Puneet

**Comment by KyQiao** [comment]
Dear Punnet,

You mean I generate a wrong size distribution? I think I validate the distribution with a histogram figure and it's indeed a power law. Could you tell me what I missed? Thank you.

Regards,
Kaiyao
________________________________
发件人: pntpareek ***@***.***>
发送时间: Friday, September 2, 2022 7:05:49 PM
收件人: KyQiao/polyLJ ***@***.***>
抄送: Kaiyao QIAO ***@***.***>; State change ***@***.***>
主题: Re: [KyQiao/polyLJ] Usage of "swap" command. (Issue #1)


Dear Kaiyao,

I have done the analysis again and found that there might be some be some issue in "generate.py" for berthier model distribution. I got correct results when I used my own code for generating the distribution.

Thanks and Regards
Puneet

―

**Comment by pntpareek** [comment]
Dear Kaiyao,

I am not sure if it is wrong or not. I was not getting the expected result but when I used my code I got the expected result. I found that for the same bin size that I use for the data generated by "generate.py" and my code, the distribution was showing close to zero values for data point in between sigma_max and sigma_min but not for the data generated by my code.

Again, this is my observation I might be wrong in the evaluation. 

P.S : - I used the following method to convert uniform distribution to power law
"https://stackoverflow.com/questions/918736/random-number-generator-that-produces-a-power-law-distribution"

Thanks and Regards
Puneet

**Comment by pntpareek** [comment]
Dear Kaiyao,

I compared the result from the two methods which is attached in the figure. I took sigma_max = 1.61111111111111 and sigma_min = 0.725 and number of points to be 100000 for both methods.

Best Regards
Puneet
![comparison](https://user-images.githubusercontent.com/109522401/188172609-943042fb-f718-4de1-8baf-01c8cf8cec17.png)

**Comment by pntpareek** [comment]
Dear Kaiyao,

I checked the two methods which you can find in the figure below. I took sigma_max = 1.61111111111111 and sigma_min = 0.725 for 100000 points. I should point that the method used by you is similar to the method I mentioned.


I think there is one difference, the random numbers generated in "generate.py" are in the range [0,1), whereas it is required that it should be [0,1]. I do not if it makes any major difference. This is the only difference I can think of right now. 

Thanks and Regards
Puneet
![comparison](https://user-images.githubusercontent.com/109522401/188181453-8462f550-577f-484c-88a8-0eac5e5b8b0b.png)

**Comment by KyQiao** [comment]
Dear Puneet,

Thanks. You're right, I wrongly used the inverse function, and it turns out gives a very close distribution with A/x^3 so I didn't check that again.

I check those two methods. The one in Mathworld makes more sense. Mine is just a very close answer, but not correct.

The range [0,1) and [0,1] will not make too much differences, it differ only in one point.


Regards,
Kaiyao
________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your reply.

Best Regards
Puneet

**Comment by KyQiao** [comment]
Dear Puneet,

I guess you want to use WCA potential where the cutoff is 2^(1/6)?

The value for bin is  (max particle radius -1)*global cutoff = (1.62-1)*1.2=0.775
So bin=0.8 should be enough.

You mentioned some time ago that the behavior of the glass is not correct, can you show me some data and figures on how?
I'm busy writing a paper these days, maybe I can take a look at it when I have time.

Regards,
Kaiyao

________________________________

**Comment by pntpareek** [comment]
Dear Kaiyao,

Thanks for your reply.

I wanted to use only the repulsive part of LJ potential which was smooth upto two derivatives. When I was doing the simulations I did not make the potential smooth, which resulted in the deviation from the actual result. After making the changes I was able to reproduce the results.

Best Regards
Puneet
